### ISSUE TITLE
@ionic-native/alipay调用 方式出错

### ISSUE THREAD

**Issue by wlclass** [adam198824/cordova-plugin-alipay#1]
ionic4
`
import { Alipay } from '@ionic-native/alipay/ngx';

export class PayPage implements OnInit {
    constructor(
        private alipay: Alipay
    ) { }
}
`

通过依赖注入方式调用时,真机调试时没有问题.
但--prod打了发布包后, 
注入的alipay为空.

**Comment by adampidong** [comment]
这里面不能使用@ionic-native/alipay，我对这个package提过pr没通过，所以请单独调用，详细请看使用说明。

**Comment by wlclass** [comment]
好的.谢谢.已经通过declare let Alipay 方式调用成功. 非常感谢您.
这个问题可以在README.md上写的更明确点.  
目前README.md上写的有@ionic-native/alipay方式调用,可能会给用户带来困惑.
